### ISSUE TITLE
Examples needed

### ISSUE THREAD

**Issue by dvankley** [ojacobson/dropwizard-simple-cors#5]
This looks like a very useful library, but it's hard to pick it up easily without some examples in the documentation. The tests are somewhat helpful, but it would be great to have some straightforward examples of common usage in the README.

**Comment by ojacobson** [comment]
That's fair feedback. I left some _super_ high-level notes in the docs, but nothing really complete. I'll leave this open to remind me to write something better.

@lewisd32 any chance you want to take a crack at this? It might take me a while to put something together, whereas I seem to recall you're using this on a regular basis right now.

**Comment by ecumali** [comment]
Example will be very helpful

**Comment by lewisd32** [comment]
I've been meaning to get to this for a while, but I've been pretty slammed. I've finally cobbled these together from a codebase that is using this. If someone else wants to put these in a pull request to add to the documentation, that would be awesome. I don't know when I'll be able to get to that.

Your configuration needs to implement `CrossOriginFilterFactoryHolder`:
```Java
import io.dropwizard.Configuration;
import ca.grimoire.dropwizard.cors.config.CrossOriginFilterFactory;
import ca.grimoire.dropwizard.cors.config.CrossOriginFilterFactoryHolder;

public class MyConfiguration extends Configuration implements CrossOriginFilterFactoryHolder {
    private CrossOriginFilterFactory cors = new CrossOriginFilterFactory();
    
    public void setCors(final CrossOriginFilterFactory cors) {
        this.cors = cors;
    }

    @Override
    public CrossOriginFilterFactory getCors() {
        return cors;
    }
}
```

And then in your `Application` class, you need to add the `CorsBundle`:
```Java
import ca.grimoire.dropwizard.cors.CorsBundle;

import io.dropwizard.Application;
import io.dropwizard.setup.Bootstrap;

public class MyApplication extends Application<MyConfiguration> {

    @Override
    public void initialize(final Bootstrap<MyConfiguration> bootstrap) {
        bootstrap.addBundle(new CorsBundle<MyConfiguration>());
    }

}
```

In your application's config file, you can do this if you simply want to allow everything:
```YAML
cors:
  origins: "*"
```
I make no statements about the advisability of configuring CORS that way. Your needs may differ.

**Comment by lewisd32** [comment]
I found time after all. :smile:

**Comment by ojacobson** [comment]
I've been out of town - so I didn't have a chance to look at this until now. Thanks for submitting a patch!
